apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:eks:us-west-2:472858849231:nodegroup/eks-stack-EKS-Cluster/WorkerNode-etIHe7sl69AL/ceb8c22c-f41e-23a5-a523-2711a0894d04
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
